### ISSUE TITLE
Feature Request: Support Sophisticated Backpacks' jukebox upgrade

### ISSUE THREAD

**Issue by HySand** [croissantnova/SanityDescentIntoMadness#11] opened 2023-08-14 14:54 UTC
Sophisticated Backpacks' jukebox upgrade allow players play music disks in ther backpacks, which will not effect sanity like jukebox.

**Comment by croissantnova** [comment] 2023-08-15 04:43
Duplicate of #7.

**Closed as completed by croissantnova** 2023-08-15 04:43 UTC
